service: rental
provider:
  name: aws
  runtime: nodejs12.x
  cfnRole: arn:aws:iam::718523126320:role/serverless
  stage: prod
  environment:
    locationIQKey: ${ssm:/home/locationIQKey~true}

functions:
  app:
    handler: handler.rental
    events:
        - http: ANY /
        - http: 'ANY {proxy+}'

plugins:
  - serverless-offline
