service: rental
provider:
  name: aws
  runtime: nodejs12.x
  cfnRole: arn:aws:iam::718523126320:role/serverless
  stage: prod
  environment:
    locationIQKey: ${ssm:/home/locationIQKey~true}

functions:
  app:
    handler: handler.rental
    events:
        - http: ANY /
        - http: 'ANY {proxy+}'


resources:
  Resources:
    CognitoUserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        MfaConfiguration: OFF
        UserPoolName: rentalUsers
        UsernameAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: False
            RequireNumbers: True
            RequireSymbols: False
            RequireUppercase: True
    CognitoUserPoolClient:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName: rental
        GenerateSecret: False
        UserPoolId:
          Ref: CognitoUserPool

plugins:
  - serverless-offline
