service: homeUI
provider:
  name: aws
  runtime: nodejs12.x
  cfnRole: arn:aws:iam::718523126320:role/serverless
  stage: prod
#  region: us-east-1

functions:
  app:
    handler: handler.homeUI
    events:
        - http: ANY /
        - http: 'ANY {proxy+}'
plugins:
  - serverless-offline